# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-01 21:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=32)),
                ('scope', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Driver Networks',
            },
        ),
        migrations.CreateModel(
            name='DriverVolumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=32)),
                ('scope', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Driver Volumes',
            },
        ),
        migrations.CreateModel(
            name='LogsLoginLogout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='User')),
                ('action', models.CharField(max_length=32, verbose_name='Messages')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Logs Login User',
            },
        ),
        migrations.CreateModel(
            name='LogsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='User')),
                ('action', models.CharField(max_length=32, verbose_name='Action')),
                ('feature', models.CharField(max_length=32, verbose_name='Feature')),
                ('message', models.CharField(max_length=256, verbose_name='Messages')),
                ('container', models.CharField(max_length=32, verbose_name='Container')),
                ('node', models.CharField(max_length=32, verbose_name='Node')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Logs Action User',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
            ],
            options={
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarm_ui.Permissions', verbose_name='permission')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'User Permissions',
            },
        ),
    ]
